spring:
  application:
    name: wallstreet
  datasource:
    #url: ${datesourceUrl}
    url: jdbc:mysql://localhost:3306/shares?serverTimezone=Asia/Shanghai
    username: root
    password: xujinjing
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      #\u8FDE\u63A5\u8D85\u65F6\u65F6\u957F
      connection-timeout: 60000
      #\u7A7A\u95F2\u8FDE\u63A5\u8D85\u65F6\u65F6\u957F
      idle-timeout: 60000
      #\u6700\u5927\u751F\u547D\u5468\u671F\uFF0C0\u4E0D\u8FC7\u671F
      max-lifetime: 0
      #\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\u6570
      minimum-idle: 10
      #\u6700\u5927\u8FDE\u63A5\u6570\u91CF
      maximum-pool-size: 10
  task:
    scheduling:
      pool:
        #\u914D\u7F6E\u53EF\u7528\u5B9A\u65F6\u4EFB\u52A1\u7EBF\u7A0B\u6570\u4E3A10\uFF0C\u907F\u514D\u7EBF\u7A0B\u963B\u585E
        size: 10
  mail:
    host: smtp.126.com
    username: jackiexu92@126.com
    password: ETBULYBLCDUXFDAU
    default-encoding: UTF-8

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/
  instance:
    prefer-ip-address: true

mybatis:
  type-aliases-package: com.jackie.wallstreet.entity
  #\u5F00\u542F\u9A7C\u5CF0\u6620\u5C04
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8081